/* Generated by scripts/generate-athletes-data.mjs — do not edit by hand */
const ATHLETES = {
  "marcus-lane": {
    "name": "Marcus Lane",
    "position": "QB · Class of 2027",
    "photo": "ML",
    "agent": "Luke Bramwell",
    "athleticLevel": "5-Star QB · National #1",
    "hometown": "Phoenix, Arizona",
    "university": "University of Texas",
    "presentability": "Executive-ready on camera; trusted in live interview settings",
    "bio": "Marcus is a dual-threat quarterback known for command at the line and poise in high-pressure drives. He is active in local youth camps and is consistently one of the strongest interview performers in his class.",
    "accomplishments": [
      "Elite 11 finalist",
      "State champion (2025)",
      "Regional NIL camp ambassador"
    ],
    "stats": [
      [
        "3,847",
        "Passing yards"
      ],
      [
        "32",
        "Touchdowns"
      ],
      [
        "68.4%",
        "Completion rate"
      ],
      [
        "5-Star",
        "Recruit rating"
      ],
      [
        "#1",
        "National rank"
      ],
      [
        "9.2",
        "QBR"
      ]
    ],
    "status": "committed",
    "from": {
      "name": "Phoenix Heritage HS",
      "logo": "PH",
      "color": "#7c1d1d"
    },
    "to": {
      "name": "University of Texas",
      "logo": "UT",
      "color": "#bf5700",
      "logoSrc": "assets/schools/texas.png"
    },
    "signed": "February 14, 2026",
    "basketball": false,
    "photoSrc": "assets/portraits/athletes/marcus-lane.jpg",
    "photoPosition": "center 36%"
  },
  "caleb-mooney": {
    "name": "Caleb Mooney",
    "position": "WR · Junior",
    "photo": "CM",
    "agent": "Luke Bramwell",
    "status": "represented",
    "athleticLevel": "Top-10 National WR",
    "hometown": "Baton Rouge, Louisiana",
    "university": "LSU",
    "presentability": "Charismatic speaker with high fan-event conversion",
    "bio": "Caleb is an explosive receiver with high route discipline and consistent production against top competition. He brings high energy to community and fan activations, especially youth-focused events.",
    "accomplishments": [
      "All-Conference selection",
      "1,200+ receiving yards season",
      "Team captain"
    ],
    "stats": [
      [
        "1,210",
        "Receiving yards"
      ],
      [
        "9",
        "Touchdowns"
      ],
      [
        "16.8",
        "Yards per catch"
      ],
      [
        "All-Conf",
        "Conference honors"
      ],
      [
        "#8",
        "National WR rank"
      ],
      [
        "78",
        "Receptions"
      ]
    ],
    "from": {
      "name": "Baton Rouge High",
      "logo": "BR",
      "color": "#461d7c"
    },
    "to": {
      "name": "LSU",
      "logo": "LSU",
      "color": "#461d7c"
    },
    "basketball": false,
    "photoSrc": "assets/portraits/athletes/caleb-mooney.jpg",
    "photoPosition": "center 36%"
  },
  "trey-holloway": {
    "name": "Trey Holloway",
    "position": "Edge · Class of 2026",
    "photo": "TH",
    "agent": "Luke Bramwell",
    "status": "represented",
    "athleticLevel": "Top-10 National Edge",
    "hometown": "Atlanta, Georgia",
    "university": "University of Georgia",
    "presentability": "Disciplined spokesperson with strong team-first tone",
    "bio": "Trey is a disruptive edge rusher with elite closing speed and disciplined technique. His personality and communication style perform well for team culture, performance, and training-focused campaigns.",
    "accomplishments": [
      "5-Star recruit",
      "17.5 sacks in season",
      "Defensive MVP (state final)"
    ],
    "stats": [
      [
        "17.5",
        "Sacks"
      ],
      [
        "74",
        "Tackles"
      ],
      [
        "12",
        "Tackles for loss"
      ],
      [
        "Top-10",
        "National rank"
      ],
      [
        "4",
        "Forced fumbles"
      ],
      [
        "5-Star",
        "Recruit rating"
      ]
    ],
    "from": {
      "name": "Westlake High",
      "logo": "WL",
      "color": "#ba0c2f"
    },
    "to": {
      "name": "University of Georgia",
      "logo": "UGA",
      "color": "#ba0c2f"
    },
    "basketball": false,
    "photoSrc": "assets/portraits/athletes/trey-holloway.jpg",
    "photoPosition": "center 38%"
  },
  "devon-park": {
    "name": "Devon Park",
    "position": "RB · Senior",
    "photo": "DP",
    "agent": "Luke Bramwell",
    "athleticLevel": "Top-3 National RB",
    "hometown": "Eugene, Oregon",
    "university": "Ohio State University",
    "presentability": "Veteran media presence; polished in long-form interviews",
    "bio": "Devon is a versatile running back with downhill power and proven receiving production. He offers immediate credibility for performance, apparel, and leadership-driven brand stories.",
    "accomplishments": [
      "Heisman watch list",
      "1,500+ rushing yards",
      "18 total touchdowns"
    ],
    "stats": [
      [
        "1,560",
        "Rushing yards"
      ],
      [
        "18",
        "Touchdowns"
      ],
      [
        "5.8",
        "Yards per carry"
      ],
      [
        "Heisman",
        "Watch list"
      ],
      [
        "#3",
        "National RB rank"
      ],
      [
        "52",
        "Receptions"
      ]
    ],
    "status": "portal",
    "from": {
      "name": "University of Oregon",
      "logo": "OR",
      "color": "#154733",
      "logoSrc": "assets/schools/oregon.png"
    },
    "to": {
      "name": "Ohio State University",
      "logo": "OSU",
      "color": "#a71930",
      "logoSrc": "assets/schools/ohio-state.png"
    },
    "signed": "January 30, 2026",
    "basketball": false,
    "photoSrc": "assets/portraits/athletes/devon-park.jpg",
    "photoPosition": "center 30%"
  },
  "jordan-blake": {
    "name": "Jordan Blake",
    "position": "QB · Class of 2026",
    "photo": "JB",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "4-Star Pro-Style QB",
    "hometown": "Dallas, Texas",
    "university": "University of Alabama",
    "presentability": "Clean social presence with national reach",
    "bio": "Jordan is a represented football athlete at University of Alabama, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Dallas HS",
      "logo": "JB",
      "color": "#9e1b32"
    },
    "to": {
      "name": "University of Alabama",
      "logo": "UA",
      "color": "#9e1b32"
    },
    "photoSrc": "assets/portraits/athletes/jordan-blake.jpg",
    "photoPosition": "center 30%"
  },
  "malik-rivers": {
    "name": "Malik Rivers",
    "position": "WR · Sophomore",
    "photo": "MR",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "All-Conference WR",
    "hometown": "Miami, Florida",
    "university": "University of Miami",
    "presentability": "High community engagement and fan-event conversion",
    "bio": "Malik is a represented football athlete at University of Miami, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Miami HS",
      "logo": "MR",
      "color": "#f47321"
    },
    "to": {
      "name": "University of Miami",
      "logo": "MIA",
      "color": "#f47321"
    },
    "photoSrc": "assets/portraits/athletes/malik-rivers.jpg",
    "photoPosition": "center 30%"
  },
  "chris-dalton": {
    "name": "Chris Dalton",
    "position": "TE · Junior",
    "photo": "CD",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "Mackey Award Watch",
    "hometown": "Columbus, Ohio",
    "university": "Ohio State University",
    "presentability": "High community engagement and fan-event conversion",
    "bio": "Chris is a represented football athlete at Ohio State University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Columbus HS",
      "logo": "CD",
      "color": "#041e42"
    },
    "to": {
      "name": "Ohio State University",
      "logo": "PSU",
      "color": "#041e42"
    },
    "photoSrc": "assets/portraits/athletes/chris-dalton.jpg",
    "photoPosition": "center 38%"
  },
  "andre-coleman": {
    "name": "Andre Coleman",
    "position": "OT · Senior",
    "photo": "AC",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "All-American OL",
    "hometown": "Birmingham, Alabama",
    "university": "University of Alabama",
    "presentability": "Polished on camera with strong sponsor alignment",
    "bio": "Andre is a represented football athlete at University of Alabama, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Birmingham HS",
      "logo": "AC",
      "color": "#9e1b32"
    },
    "to": {
      "name": "University of Alabama",
      "logo": "UA",
      "color": "#9e1b32"
    },
    "photoSrc": "assets/portraits/athletes/andre-coleman.jpg",
    "photoPosition": "center 38%"
  },
  "tyler-nash": {
    "name": "Tyler Nash",
    "position": "CB · Class of 2027",
    "photo": "TN",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "Top-15 National CB",
    "hometown": "Charlotte, North Carolina",
    "university": "Clemson University",
    "presentability": "High community engagement and fan-event conversion",
    "bio": "Tyler is a represented football athlete at Clemson University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Charlotte HS",
      "logo": "TN",
      "color": "#f56600"
    },
    "to": {
      "name": "Clemson University",
      "logo": "CLEM",
      "color": "#f56600"
    },
    "photoSrc": "assets/portraits/athletes/tyler-nash.jpg",
    "photoPosition": "center 32%"
  },
  "ryan-mercer": {
    "name": "Ryan Mercer",
    "position": "LB · Junior",
    "photo": "RM",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "Butkus Award Candidate",
    "hometown": "Nashville, Tennessee",
    "university": "University of Tennessee",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Ryan is a represented football athlete at University of Tennessee, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Nashville HS",
      "logo": "RM",
      "color": "#ff8200"
    },
    "to": {
      "name": "University of Tennessee",
      "logo": "TENN",
      "color": "#ff8200"
    },
    "photoSrc": "assets/portraits/athletes/ryan-mercer.jpg",
    "photoPosition": "center 36%"
  },
  "darius-webb": {
    "name": "Darius Webb",
    "position": "RB · Class of 2026",
    "photo": "DW",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "4-Star All-Purpose Back",
    "hometown": "Houston, Texas",
    "university": "Texas A&M",
    "presentability": "Trusted voice for performance and lifestyle brands",
    "bio": "Darius is a represented football athlete at Texas A&M, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Houston HS",
      "logo": "DW",
      "color": "#500000"
    },
    "to": {
      "name": "Texas A&M",
      "logo": "TAMU",
      "color": "#500000"
    },
    "photoSrc": "assets/portraits/athletes/darius-webb.jpg",
    "photoPosition": "center 38%"
  },
  "noah-griffin": {
    "name": "Noah Griffin",
    "position": "Edge · Sophomore",
    "photo": "NG",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "Double-Digit Sack Season",
    "hometown": "State College, Pennsylvania",
    "university": "Penn State",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Noah is a represented football athlete at Penn State, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "State College HS",
      "logo": "NG",
      "color": "#041e42"
    },
    "to": {
      "name": "Penn State",
      "logo": "PSU",
      "color": "#041e42"
    },
    "photoSrc": "assets/portraits/athletes/noah-griffin.jpg",
    "photoPosition": "center 36%"
  },
  "ethan-brooks": {
    "name": "Ethan Brooks",
    "position": "S · Senior",
    "photo": "EB",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "Thorpe Award Semifinalist",
    "hometown": "Tampa, Florida",
    "university": "University of Florida",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Ethan is a represented football athlete at University of Florida, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Tampa HS",
      "logo": "EB",
      "color": "#0021a5"
    },
    "to": {
      "name": "University of Florida",
      "logo": "UF",
      "color": "#0021a5"
    },
    "photoSrc": "assets/portraits/athletes/ethan-brooks.jpg",
    "photoPosition": "center 28%"
  },
  "jamal-ortiz": {
    "name": "Jamal Ortiz",
    "position": "WR · Class of 2027",
    "photo": "JO",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "Top-20 National WR",
    "hometown": "Los Angeles, California",
    "university": "USC",
    "presentability": "Polished on camera with strong sponsor alignment",
    "bio": "Jamal is a represented football athlete at USC, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Los Angeles HS",
      "logo": "JO",
      "color": "#990000"
    },
    "to": {
      "name": "USC",
      "logo": "USC",
      "color": "#990000"
    },
    "photoSrc": "assets/portraits/athletes/jamal-ortiz.jpg",
    "photoPosition": "center 34%"
  },
  "cameron-ellis": {
    "name": "Cameron Ellis",
    "position": "DL · Junior",
    "photo": "CE",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "All-Power Four Interior",
    "hometown": "Detroit, Michigan",
    "university": "University of Michigan",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Cameron is a represented football athlete at University of Michigan, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Detroit HS",
      "logo": "CE",
      "color": "#00274c"
    },
    "to": {
      "name": "University of Michigan",
      "logo": "MICH",
      "color": "#00274c"
    },
    "photoSrc": "assets/portraits/athletes/cameron-ellis.jpg",
    "photoPosition": "center 36%"
  },
  "logan-pierce": {
    "name": "Logan Pierce",
    "position": "QB · Sophomore",
    "photo": "LP",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "Rising Portal QB",
    "hometown": "Norman, Oklahoma",
    "university": "University of Oklahoma",
    "presentability": "High community engagement and fan-event conversion",
    "bio": "Logan is a represented football athlete at University of Oklahoma, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Norman HS",
      "logo": "LP",
      "color": "#841617"
    },
    "to": {
      "name": "University of Oklahoma",
      "logo": "OU",
      "color": "#841617"
    },
    "photoSrc": "assets/portraits/athletes/logan-pierce.jpg",
    "photoPosition": "center 32%"
  },
  "isaiah-grant": {
    "name": "Isaiah Grant",
    "position": "CB · Junior",
    "photo": "IG",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "Lockdown Corner",
    "hometown": "Seattle, Washington",
    "university": "University of Washington",
    "presentability": "Clean social presence with national reach",
    "bio": "Isaiah is a represented football athlete at University of Washington, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Seattle HS",
      "logo": "IG",
      "color": "#4b2e83"
    },
    "to": {
      "name": "University of Washington",
      "logo": "UW",
      "color": "#4b2e83"
    },
    "photoSrc": "assets/portraits/athletes/isaiah-grant.jpg",
    "photoPosition": "center 36%"
  },
  "mason-reid": {
    "name": "Mason Reid",
    "position": "LB · Class of 2026",
    "photo": "MR",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "4-Star Instinct Linebacker",
    "hometown": "Madison, Wisconsin",
    "university": "University of Wisconsin",
    "presentability": "Trusted voice for performance and lifestyle brands",
    "bio": "Mason is a represented football athlete at University of Wisconsin, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Madison HS",
      "logo": "MR",
      "color": "#c5050c"
    },
    "to": {
      "name": "University of Wisconsin",
      "logo": "WISC",
      "color": "#c5050c"
    },
    "photoSrc": "assets/portraits/athletes/mason-reid.jpg",
    "photoPosition": "center 34%"
  },
  "cole-bennett": {
    "name": "Cole Bennett",
    "position": "K · Senior",
    "photo": "CB",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "Lou Groza Award Finalist",
    "hometown": "Auburn, Alabama",
    "university": "Auburn University",
    "presentability": "Clean social presence with national reach",
    "bio": "Cole is a represented football athlete at Auburn University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Auburn HS",
      "logo": "CB",
      "color": "#0c2340"
    },
    "to": {
      "name": "Auburn University",
      "logo": "AUB",
      "color": "#0c2340"
    },
    "photoSrc": "assets/portraits/athletes/cole-bennett.jpg",
    "photoPosition": "center 34%"
  },
  "victor-santos": {
    "name": "Victor Santos",
    "position": "WR · Senior",
    "photo": "VS",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "1,000+ Yard Receiver",
    "hometown": "San Antonio, Texas",
    "university": "University of Texas",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Victor is a represented football athlete at University of Texas, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "San Antonio HS",
      "logo": "VS",
      "color": "#f56600"
    },
    "to": {
      "name": "University of Texas",
      "logo": "CLEM",
      "color": "#f56600"
    },
    "photoSrc": "assets/portraits/athletes/victor-santos.jpg",
    "photoPosition": "center 36%"
  },
  "grant-holloway": {
    "name": "Grant Holloway",
    "position": "OL · Junior",
    "photo": "GH",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "Multi-Year Starter",
    "hometown": "South Bend, Indiana",
    "university": "University of Notre Dame",
    "presentability": "Clean social presence with national reach",
    "bio": "Grant is a represented football athlete at University of Notre Dame, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "South Bend HS",
      "logo": "GH",
      "color": "#0c2340"
    },
    "to": {
      "name": "University of Notre Dame",
      "logo": "ND",
      "color": "#0c2340"
    },
    "photoSrc": "assets/portraits/athletes/grant-holloway.jpg",
    "photoPosition": "center 32%"
  },
  "parker-walsh": {
    "name": "Parker Walsh",
    "position": "Edge · Class of 2027",
    "photo": "PW",
    "basketball": false,
    "agent": "Luke Bramwell",
    "athleticLevel": "Top-25 National Edge",
    "hometown": "Palo Alto, California",
    "university": "Stanford University",
    "presentability": "Polished on camera with strong sponsor alignment",
    "bio": "Parker is a represented football athlete at Stanford University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Palo Alto HS",
      "logo": "PW",
      "color": "#8c1515"
    },
    "to": {
      "name": "Stanford University",
      "logo": "STAN",
      "color": "#8c1515"
    },
    "photoSrc": "assets/portraits/athletes/parker-walsh.jpg",
    "photoPosition": "center 36%"
  },
  "terrell-knox": {
    "name": "Terrell Knox",
    "position": "RB · Junior",
    "photo": "TK",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "Workhorse Back",
    "hometown": "Jacksonville, Florida",
    "university": "University of Florida",
    "presentability": "High community engagement and fan-event conversion",
    "bio": "Terrell is a represented football athlete at University of Florida, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Jacksonville HS",
      "logo": "TK",
      "color": "#0021a5"
    },
    "to": {
      "name": "University of Florida",
      "logo": "UF",
      "color": "#0021a5"
    },
    "photoSrc": "assets/portraits/athletes/terrell-knox.jpg",
    "photoPosition": "center 36%"
  },
  "sean-murphy": {
    "name": "Sean Murphy",
    "position": "QB · Senior",
    "photo": "SM",
    "basketball": false,
    "agent": "Eli Okonkwo",
    "athleticLevel": "Graduate Transfer QB",
    "hometown": "Tucson, Arizona",
    "university": "USC",
    "presentability": "Trusted voice for performance and lifestyle brands",
    "bio": "Sean is a represented football athlete at USC, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "All-conference honors",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "1,050",
        "Yards"
      ],
      [
        "10",
        "Touchdowns"
      ],
      [
        "All-Conf",
        "Honors"
      ],
      [
        "Top-100",
        "National rank"
      ],
      [
        "4-Star",
        "Rating"
      ],
      [
        "12",
        "Starts"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Tucson HS",
      "logo": "SM",
      "color": "#990000"
    },
    "to": {
      "name": "USC",
      "logo": "USC",
      "color": "#990000"
    },
    "photoSrc": "assets/portraits/athletes/sean-murphy.jpg",
    "photoPosition": "center 34%"
  },
  "idris-vale": {
    "name": "Idris Vale",
    "position": "PG · Class of 2026",
    "photo": "IV",
    "agent": "Lenny Vasquez",
    "athleticLevel": "Top-25 National Guard",
    "hometown": "Newark, New Jersey",
    "university": "Duke University",
    "presentability": "Strong social presence with clean brand alignment history",
    "bio": "Idris is a scoring point guard with advanced pace control and high-assist playmaking. Off the floor, he is known for polished social content and a dependable, sponsor-friendly media style.",
    "accomplishments": [
      "Jordan Brand Classic invite",
      "EYBL All-Circuit First Team",
      "State Player of the Year finalist"
    ],
    "stats": [
      [
        "24.3",
        "Points per game"
      ],
      [
        "7.2",
        "Assists"
      ],
      [
        "4.1",
        "Rebounds"
      ],
      [
        "Top-25",
        "National rank"
      ],
      [
        "43%",
        "3-point %"
      ],
      [
        "18",
        "Games played"
      ]
    ],
    "status": "signed",
    "from": {
      "name": "Montverde Academy",
      "logo": "MN",
      "color": "#3d3d3d"
    },
    "to": {
      "name": "Duke University",
      "logo": "DUKE",
      "color": "#0d2240",
      "logoSrc": "assets/schools/duke.png"
    },
    "signed": "December 9, 2025",
    "basketball": true,
    "photoSrc": "assets/portraits/athletes/idris-vale.jpg",
    "photoPosition": "center 38%"
  },
  "sienna-hart": {
    "name": "Sienna Hart",
    "position": "SG · AAU Top 50",
    "photo": "SH",
    "agent": "Lenny Vasquez",
    "status": "represented",
    "athleticLevel": "AAU Top-50 Wing",
    "hometown": "San Diego, California",
    "university": "UCLA (commit target)",
    "presentability": "Camera-confident storyteller with premium lifestyle fit",
    "bio": "Sienna is a two-way wing whose perimeter defense and shooting range translate across systems. She is especially strong in beauty, wellness, and lifestyle storytelling partnerships.",
    "accomplishments": [
      "EYBL top scorer (regional)",
      "Top-50 AAU ranking",
      "Nike circuit standout"
    ],
    "stats": [
      [
        "19.8",
        "Points per game"
      ],
      [
        "5.4",
        "Assists"
      ],
      [
        "3.8",
        "Steals"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "41%",
        "3-point %"
      ],
      [
        "EYBL",
        "Circuit"
      ]
    ],
    "from": {
      "name": "Hoover High",
      "logo": "HV",
      "color": "#2d68c4"
    },
    "to": {
      "name": "UCLA",
      "logo": "UCLA",
      "color": "#2d68c4"
    },
    "basketball": true,
    "photoSrc": "assets/portraits/athletes/sienna-hart.jpg",
    "photoPosition": "center 34%"
  },
  "avery-collins": {
    "name": "Avery Collins",
    "position": "SF · Class of 2027",
    "photo": "AC",
    "basketball": true,
    "agent": "Sofia Ruiz",
    "athleticLevel": "Top-30 National Forward",
    "hometown": "Chicago, Illinois",
    "university": "University of Kansas",
    "presentability": "High community engagement and fan-event conversion",
    "bio": "Avery is a represented basketball athlete at University of Kansas, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Chicago HS",
      "logo": "AC",
      "color": "#0051ba"
    },
    "to": {
      "name": "University of Kansas",
      "logo": "KU",
      "color": "#0051ba"
    },
    "photoSrc": "assets/portraits/athletes/avery-collins.jpg",
    "photoPosition": "center 36%"
  },
  "miles-carter": {
    "name": "Miles Carter",
    "position": "PG · Sophomore",
    "photo": "MC",
    "basketball": true,
    "agent": "Lenny Vasquez",
    "athleticLevel": "SEC Newcomer of the Year",
    "hometown": "Lexington, Kentucky",
    "university": "University of Kentucky",
    "presentability": "Trusted voice for performance and lifestyle brands",
    "bio": "Miles is a represented basketball athlete at University of Kentucky, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Lexington HS",
      "logo": "MC",
      "color": "#0033a0"
    },
    "to": {
      "name": "University of Kentucky",
      "logo": "UK",
      "color": "#0033a0"
    },
    "photoSrc": "assets/portraits/athletes/miles-carter.jpg",
    "photoPosition": "center 34%"
  },
  "jalen-brooks": {
    "name": "Jalen Brooks",
    "position": "SG · Junior",
    "photo": "JB",
    "basketball": true,
    "agent": "Lenny Vasquez",
    "athleticLevel": "All-ACC First Team",
    "hometown": "Raleigh, North Carolina",
    "university": "University of North Carolina",
    "presentability": "Polished on camera with strong sponsor alignment",
    "bio": "Jalen is a represented basketball athlete at University of North Carolina, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Raleigh HS",
      "logo": "JB",
      "color": "#7bafd4"
    },
    "to": {
      "name": "University of North Carolina",
      "logo": "UNC",
      "color": "#7bafd4"
    },
    "photoSrc": "assets/portraits/athletes/jalen-brooks.jpg",
    "photoPosition": "center 32%"
  },
  "derek-lawson": {
    "name": "Derek Lawson",
    "position": "PF · Senior",
    "photo": "DL",
    "basketball": true,
    "agent": "Sofia Ruiz",
    "athleticLevel": "Double-Double Machine",
    "hometown": "Philadelphia, Pennsylvania",
    "university": "Villanova University",
    "presentability": "Trusted voice for performance and lifestyle brands",
    "bio": "Derek is a represented basketball athlete at Villanova University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Philadelphia HS",
      "logo": "DL",
      "color": "#00205b"
    },
    "to": {
      "name": "Villanova University",
      "logo": "NOVA",
      "color": "#00205b"
    },
    "photoSrc": "assets/portraits/athletes/derek-lawson.jpg",
    "photoPosition": "center 36%"
  },
  "kai-mendoza": {
    "name": "Kai Mendoza",
    "position": "C · Class of 2026",
    "photo": "KM",
    "basketball": true,
    "agent": "Lenny Vasquez",
    "athleticLevel": "Rim-Protecting Big",
    "hometown": "Spokane, Washington",
    "university": "Gonzaga University",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Kai is a represented basketball athlete at Gonzaga University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Spokane HS",
      "logo": "KM",
      "color": "#c8102e"
    },
    "to": {
      "name": "Gonzaga University",
      "logo": "ZAG",
      "color": "#c8102e"
    },
    "photoSrc": "assets/portraits/athletes/kai-mendoza.jpg",
    "photoPosition": "center 36%"
  },
  "tyrese-holland": {
    "name": "Tyrese Holland",
    "position": "PG · Junior",
    "photo": "TH",
    "basketball": true,
    "agent": "Lenny Vasquez",
    "athleticLevel": "National Champion Contributor",
    "hometown": "Hartford, Connecticut",
    "university": "UConn",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Tyrese is a represented basketball athlete at UConn, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Hartford HS",
      "logo": "TH",
      "color": "#000e2f"
    },
    "to": {
      "name": "UConn",
      "logo": "UCONN",
      "color": "#000e2f"
    },
    "photoSrc": "assets/portraits/athletes/tyrese-holland.jpg",
    "photoPosition": "center 34%"
  },
  "brandon-tate": {
    "name": "Brandon Tate",
    "position": "SF · Sophomore",
    "photo": "BT",
    "basketball": true,
    "agent": "Sofia Ruiz",
    "athleticLevel": "Two-Way Wing",
    "hometown": "Houston, Texas",
    "university": "Houston",
    "presentability": "High community engagement and fan-event conversion",
    "bio": "Brandon is a represented basketball athlete at Houston, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Houston HS",
      "logo": "BT",
      "color": "#c8102e"
    },
    "to": {
      "name": "Houston",
      "logo": "HOU",
      "color": "#c8102e"
    },
    "photoSrc": "assets/portraits/athletes/brandon-tate.jpg",
    "photoPosition": "center 34%"
  },
  "nico-alvarez": {
    "name": "Nico Alvarez",
    "position": "SG · Class of 2027",
    "photo": "NA",
    "basketball": true,
    "agent": "Lenny Vasquez",
    "athleticLevel": "Elite Shooter",
    "hometown": "Milwaukee, Wisconsin",
    "university": "Marquette University",
    "presentability": "Trusted voice for performance and lifestyle brands",
    "bio": "Nico is a represented basketball athlete at Marquette University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Milwaukee HS",
      "logo": "NA",
      "color": "#003366"
    },
    "to": {
      "name": "Marquette University",
      "logo": "MARQ",
      "color": "#003366"
    },
    "photoSrc": "assets/portraits/athletes/nico-alvarez.jpg",
    "photoPosition": "center 36%"
  },
  "jordan-ellis": {
    "name": "Jordan Ellis",
    "position": "PF · Junior",
    "photo": "JE",
    "basketball": true,
    "agent": "Lenny Vasquez",
    "athleticLevel": "Big 12 Defensive Player",
    "hometown": "Waco, Texas",
    "university": "Baylor University",
    "presentability": "Executive-ready in interview and activation settings",
    "bio": "Jordan is a represented basketball athlete at Baylor University, known for consistent on-field production and a professional approach to NIL and media opportunities.",
    "accomplishments": [
      "Circuit standout",
      "Team captain or leadership role",
      "Community camp ambassador"
    ],
    "stats": [
      [
        "18.5",
        "Points per game"
      ],
      [
        "4.2",
        "Rebounds"
      ],
      [
        "3.1",
        "Assists"
      ],
      [
        "Top-50",
        "National rank"
      ],
      [
        "38%",
        "3-point %"
      ],
      [
        "32",
        "Games played"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Waco HS",
      "logo": "JE",
      "color": "#154734"
    },
    "to": {
      "name": "Baylor University",
      "logo": "BAY",
      "color": "#154734"
    },
    "photoSrc": "assets/portraits/athletes/jordan-ellis.jpg",
    "photoPosition": "center 30%"
  }
};
