/* Generated by scripts/generate-athletes-data.mjs — do not edit by hand */
const ATHLETE_ORDER = [
  "salahadin-allah",
  "jaiden-allos",
  "quory-ambrose",
  "maddox-arnold",
  "sean-brady",
  "rj-chapman",
  "shacre-colwell",
  "malik-diaby",
  "fabian-duncan",
  "jamai-east",
  "aeron-gresham",
  "jr-hays",
  "nick-herman",
  "wynden-ho-ohuli",
  "chris-kalu",
  "dj-kelly",
  "nic-lendino",
  "tre-leonard",
  "justin-montgomery",
  "jason-oliver",
  "justin-ross",
  "tyrell-russell",
  "trajan-sinatra",
  "calvin-smith-jr",
  "cal-swanson",
  "mytrell-tillman"
];
const ATHLETES = {
  "salahadin-allah": {
    "name": "Salahadin Allah",
    "position": "RB · Junior",
    "photo": "SA",
    "basketball": false,
    "agent": "Luke Mazur",
    "athleticLevel": "Junior · Iowa State",
    "hometown": "La Marque, TX",
    "university": "Iowa State",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Salahadin is a represented football athlete at Iowa State, based in La Marque, TX.",
    "accomplishments": [
      "Junior · RB",
      "Represented at Iowa State",
      "Based in La Marque, TX"
    ],
    "stats": [
      [
        "RB",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "I",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Luke",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Oregon State",
      "logo": "O",
      "color": "hsl(317 42% 34%)",
      "logoSrc": "assets/schools/oregon-state.png"
    },
    "to": {
      "name": "Iowa State",
      "logo": "I",
      "color": "hsl(201 42% 34%)",
      "logoSrc": "assets/schools/iowa-state.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/salahadin-allah.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "jaiden-allos": {
    "name": "Jaiden Allos",
    "position": "LB · Sophomore",
    "photo": "JA",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Sophomore · Mercyhurst",
    "hometown": "West Bloomfield, MI",
    "university": "Mercyhurst",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Jaiden is a represented football athlete at Mercyhurst, based in West Bloomfield, MI.",
    "accomplishments": [
      "Sophomore · LB",
      "Represented at Mercyhurst",
      "Based in West Bloomfield, MI"
    ],
    "stats": [
      [
        "LB",
        "Position"
      ],
      [
        "Sophomore",
        "Class"
      ],
      [
        "M",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "West Bloomfield area",
      "logo": "JA",
      "color": "#3C096C"
    },
    "to": {
      "name": "Mercyhurst",
      "logo": "M",
      "color": "hsl(302 42% 34%)",
      "logoSrc": "assets/schools/mercyhurst.png"
    },
    "photoSrc": "assets/portraits/athletes/jaiden-allos.jpg",
    "photoPosition": "center 0%",
    "photoPositionRoster": "center 0%"
  },
  "quory-ambrose": {
    "name": "Quory Ambrose",
    "position": "OL · Junior",
    "photo": "QA",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Junior · Harding",
    "hometown": "Jacksonville, FL",
    "university": "Harding",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Quory is a represented football athlete at Harding, based in Jacksonville, FL.",
    "accomplishments": [
      "Junior · OL",
      "Represented at Harding",
      "Based in Jacksonville, FL"
    ],
    "stats": [
      [
        "OL",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "H",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Presbyterian",
      "logo": "P",
      "color": "hsl(276 42% 34%)",
      "logoSrc": "assets/schools/presbyterian.png"
    },
    "to": {
      "name": "Harding",
      "logo": "H",
      "color": "hsl(311 42% 34%)",
      "logoSrc": "assets/schools/harding.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/quory-ambrose.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "maddox-arnold": {
    "name": "Maddox Arnold",
    "position": "LB · Redshirt Freshman",
    "photo": "MA",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Redshirt Freshman · Toledo",
    "hometown": "Cincinnati, OH",
    "university": "Toledo",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Maddox is a represented football athlete at Toledo, based in Cincinnati, OH.",
    "accomplishments": [
      "Redshirt Freshman · LB",
      "Represented at Toledo",
      "Based in Cincinnati, OH"
    ],
    "stats": [
      [
        "LB",
        "Position"
      ],
      [
        "Redshirt Freshman",
        "Class"
      ],
      [
        "T",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Cincinnati area",
      "logo": "MA",
      "color": "#3C096C"
    },
    "to": {
      "name": "Toledo",
      "logo": "T",
      "color": "hsl(135 42% 34%)",
      "logoSrc": "assets/schools/toledo.png"
    },
    "photoSrc": "assets/portraits/athletes/maddox-arnold.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "sean-brady": {
    "name": "Sean Brady",
    "position": "WR · Redshirt Freshman",
    "photo": "SB",
    "basketball": false,
    "agent": "Luke Mazur",
    "athleticLevel": "Redshirt Freshman · Gardner-Webb",
    "hometown": "Charlotte, NC",
    "university": "Gardner-Webb",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Sean is a represented football athlete at Gardner-Webb, based in Charlotte, NC.",
    "accomplishments": [
      "Redshirt Freshman · WR",
      "Represented at Gardner-Webb",
      "Based in Charlotte, NC"
    ],
    "stats": [
      [
        "WR",
        "Position"
      ],
      [
        "Redshirt Freshman",
        "Class"
      ],
      [
        "G",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Luke",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Charlotte area",
      "logo": "SB",
      "color": "#3C096C"
    },
    "to": {
      "name": "Gardner-Webb",
      "logo": "G",
      "color": "hsl(260 42% 34%)",
      "logoSrc": "assets/schools/gardner-webb.png"
    },
    "photoSrc": "assets/portraits/athletes/sean-brady.jpg",
    "photoPosition": "center center",
    "photoPositionRoster": "center center"
  },
  "rj-chapman": {
    "name": "RJ Chapman",
    "position": "DB · Senior",
    "photo": "RC",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Senior · New Mexico State",
    "hometown": "Accokeek, MD",
    "university": "New Mexico State",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "RJ is a represented football athlete at New Mexico State, based in Accokeek, MD.",
    "accomplishments": [
      "Senior · DB",
      "Represented at New Mexico State",
      "Based in Accokeek, MD"
    ],
    "stats": [
      [
        "DB",
        "Position"
      ],
      [
        "Senior",
        "Class"
      ],
      [
        "NM",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Merrimack",
      "logo": "M",
      "color": "hsl(157 42% 34%)",
      "logoSrc": "assets/schools/merrimack.png"
    },
    "to": {
      "name": "New Mexico State",
      "logo": "NM",
      "color": "hsl(126 42% 34%)",
      "logoSrc": "assets/schools/new-mexico-state.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/rj-chapman.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "shacre-colwell": {
    "name": "Shacre Colwell",
    "position": "WR · Freshman",
    "photo": "SC",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Freshman · Bryant",
    "hometown": "Betlehem, PA",
    "university": "Bryant",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Shacre is a represented football athlete at Bryant, based in Betlehem, PA.",
    "accomplishments": [
      "Freshman · WR",
      "Represented at Bryant",
      "Based in Betlehem, PA"
    ],
    "stats": [
      [
        "WR",
        "Position"
      ],
      [
        "Freshman",
        "Class"
      ],
      [
        "B",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Betlehem area",
      "logo": "SC",
      "color": "#3C096C"
    },
    "to": {
      "name": "Bryant",
      "logo": "B",
      "color": "hsl(294 42% 34%)",
      "logoSrc": "assets/schools/bryant.png"
    },
    "photoSrc": "assets/portraits/athletes/shacre-colwell.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "malik-diaby": {
    "name": "Malik Diaby",
    "position": "CB · Redshirt Freshman",
    "photo": "MD",
    "basketball": false,
    "agent": "Luke Mazur",
    "athleticLevel": "Redshirt Freshman · New Hampshire",
    "hometown": "Tolland, CT",
    "university": "New Hampshire",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Malik is a represented football athlete at New Hampshire, based in Tolland, CT.",
    "accomplishments": [
      "Redshirt Freshman · CB",
      "Represented at New Hampshire",
      "Based in Tolland, CT"
    ],
    "stats": [
      [
        "CB",
        "Position"
      ],
      [
        "Redshirt Freshman",
        "Class"
      ],
      [
        "NH",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Luke",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Tolland area",
      "logo": "MD",
      "color": "#3C096C"
    },
    "to": {
      "name": "New Hampshire",
      "logo": "NH",
      "color": "hsl(243 42% 34%)",
      "logoSrc": "assets/schools/new-hampshire.png"
    },
    "photoSrc": "assets/portraits/athletes/malik-diaby.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "fabian-duncan": {
    "name": "Fabian Duncan",
    "position": "RB · Junior",
    "photo": "FD",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Junior · Johnson C. Smith",
    "hometown": "Charlotte, NC",
    "university": "Johnson C. Smith",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Fabian is a represented football athlete at Johnson C. Smith, based in Charlotte, NC.",
    "accomplishments": [
      "Junior · RB",
      "Represented at Johnson C. Smith",
      "Based in Charlotte, NC"
    ],
    "stats": [
      [
        "RB",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "JCS",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Allen",
      "logo": "A",
      "color": "hsl(162 42% 34%)",
      "logoSrc": "assets/schools/allen.png"
    },
    "to": {
      "name": "Johnson C. Smith",
      "logo": "JCS",
      "color": "hsl(151 42% 34%)",
      "logoSrc": "assets/schools/johnson-c-smith.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/fabian-duncan.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "jamai-east": {
    "name": "Jamai East",
    "position": "WR · Redshirt Junior",
    "photo": "JE",
    "basketball": false,
    "agent": "Luke Mazur",
    "athleticLevel": "Redshirt Junior · Eastern Washington",
    "hometown": "Fairfield, CA",
    "university": "Eastern Washington",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Jamai is a represented football athlete at Eastern Washington, based in Fairfield, CA.",
    "accomplishments": [
      "Redshirt Junior · WR",
      "Represented at Eastern Washington",
      "Based in Fairfield, CA"
    ],
    "stats": [
      [
        "WR",
        "Position"
      ],
      [
        "Redshirt Junior",
        "Class"
      ],
      [
        "EW",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Luke",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Oregon State",
      "logo": "O",
      "color": "hsl(317 42% 34%)",
      "logoSrc": "assets/schools/oregon-state.png"
    },
    "to": {
      "name": "Eastern Washington",
      "logo": "EW",
      "color": "hsl(28 42% 34%)",
      "logoSrc": "assets/schools/eastern-washington.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/jamai-east.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "aeron-gresham": {
    "name": "Aeron Gresham",
    "position": "CB · Junior",
    "photo": "AG",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Junior · Allen",
    "hometown": "Covington, GA",
    "university": "Allen",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Aeron is a represented football athlete at Allen, based in Covington, GA.",
    "accomplishments": [
      "Junior · CB",
      "Represented at Allen",
      "Based in Covington, GA"
    ],
    "stats": [
      [
        "CB",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "A",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Covington area",
      "logo": "AG",
      "color": "#3C096C"
    },
    "to": {
      "name": "Allen",
      "logo": "A",
      "color": "hsl(162 42% 34%)",
      "logoSrc": "assets/schools/allen.png"
    },
    "photoSrc": "assets/portraits/athletes/aeron-gresham.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "jr-hays": {
    "name": "JR Hays",
    "position": "RB · Redhshirt Sophomore",
    "photo": "JH",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Redhshirt Sophomore · Western Michigan",
    "hometown": "Florence, KY",
    "university": "Western Michigan",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "JR is a represented football athlete at Western Michigan, based in Florence, KY.",
    "accomplishments": [
      "Redhshirt Sophomore · RB",
      "Represented at Western Michigan",
      "Based in Florence, KY"
    ],
    "stats": [
      [
        "RB",
        "Position"
      ],
      [
        "Redhshirt Sophomore",
        "Class"
      ],
      [
        "WM",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Florence area",
      "logo": "JH",
      "color": "#3C096C"
    },
    "to": {
      "name": "Western Michigan",
      "logo": "WM",
      "color": "hsl(34 42% 34%)",
      "logoSrc": "assets/schools/western-michigan.png"
    },
    "photoSrc": "assets/portraits/athletes/jr-hays.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "nick-herman": {
    "name": "Nick Herman",
    "position": "RB · Sophomore",
    "photo": "NH",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Sophomore · James Madison",
    "hometown": "Chicago, IL",
    "university": "James Madison",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Nick is a represented football athlete at James Madison, based in Chicago, IL.",
    "accomplishments": [
      "Sophomore · RB",
      "Represented at James Madison",
      "Based in Chicago, IL"
    ],
    "stats": [
      [
        "RB",
        "Position"
      ],
      [
        "Sophomore",
        "Class"
      ],
      [
        "JM",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Drake",
      "logo": "D",
      "color": "hsl(37 42% 34%)",
      "logoSrc": "assets/schools/drake.png"
    },
    "to": {
      "name": "James Madison",
      "logo": "JM",
      "color": "hsl(221 42% 34%)",
      "logoSrc": "assets/schools/james-madison.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/nick-herman.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "wynden-ho-ohuli": {
    "name": "Wynden Ho'ohuli",
    "position": "DL · Senior",
    "photo": "WH",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Senior · Hawaii",
    "hometown": "Kapolei, HI",
    "university": "Hawaii",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Wynden is a represented football athlete at Hawaii, based in Kapolei, HI.",
    "accomplishments": [
      "Senior · DL",
      "Represented at Hawaii",
      "Based in Kapolei, HI"
    ],
    "stats": [
      [
        "DL",
        "Position"
      ],
      [
        "Senior",
        "Class"
      ],
      [
        "H",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Kapolei area",
      "logo": "WH",
      "color": "#3C096C"
    },
    "to": {
      "name": "Hawaii",
      "logo": "H",
      "color": "hsl(235 42% 34%)",
      "logoSrc": "assets/schools/hawaii.png"
    },
    "photoSrc": "assets/portraits/athletes/wynden-ho-ohuli.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "chris-kalu": {
    "name": "Chris Kalu",
    "position": "DL · Sophomore",
    "photo": "CK",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Sophomore · Nevada",
    "hometown": "Gilbert, AZ",
    "university": "Nevada",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Chris is a represented football athlete at Nevada, based in Gilbert, AZ.",
    "accomplishments": [
      "Sophomore · DL",
      "Represented at Nevada",
      "Based in Gilbert, AZ"
    ],
    "stats": [
      [
        "DL",
        "Position"
      ],
      [
        "Sophomore",
        "Class"
      ],
      [
        "N",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Western New Mexico",
      "logo": "WNM",
      "color": "hsl(323 42% 34%)",
      "logoSrc": "assets/schools/western-new-mexico.png"
    },
    "to": {
      "name": "Nevada",
      "logo": "N",
      "color": "hsl(111 42% 34%)",
      "logoSrc": "assets/schools/nevada.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/chris-kalu.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "dj-kelly": {
    "name": "DJ Kelly",
    "position": "CB · Redshirt Freshman",
    "photo": "DK",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Redshirt Freshman · James Madison",
    "hometown": "Allentown, PA",
    "university": "James Madison",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "DJ is a represented football athlete at James Madison, based in Allentown, PA.",
    "accomplishments": [
      "Redshirt Freshman · CB",
      "Represented at James Madison",
      "Based in Allentown, PA"
    ],
    "stats": [
      [
        "CB",
        "Position"
      ],
      [
        "Redshirt Freshman",
        "Class"
      ],
      [
        "JM",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Toledo",
      "logo": "T",
      "color": "hsl(135 42% 34%)",
      "logoSrc": "assets/schools/toledo.png"
    },
    "to": {
      "name": "James Madison",
      "logo": "JM",
      "color": "hsl(221 42% 34%)",
      "logoSrc": "assets/schools/james-madison.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/dj-kelly.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "nic-lendino": {
    "name": "Nic Lendino",
    "position": "DB · Redshirt Junior",
    "photo": "NL",
    "basketball": false,
    "agent": "Tony Storniolo",
    "athleticLevel": "Redshirt Junior · Valparaiso",
    "hometown": "Naperville, IL",
    "university": "Valparaiso",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Nic is a represented football athlete at Valparaiso, based in Naperville, IL.",
    "accomplishments": [
      "Redshirt Junior · DB",
      "Represented at Valparaiso",
      "Based in Naperville, IL"
    ],
    "stats": [
      [
        "DB",
        "Position"
      ],
      [
        "Redshirt Junior",
        "Class"
      ],
      [
        "V",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Tony",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Naperville area",
      "logo": "NL",
      "color": "#3C096C"
    },
    "to": {
      "name": "Valparaiso",
      "logo": "V",
      "color": "hsl(68 42% 34%)",
      "logoSrc": "assets/schools/valparaiso.png"
    },
    "photoSrc": "assets/portraits/athletes/nic-lendino.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "tre-leonard": {
    "name": "Tre Leonard",
    "position": "RB · Redshirt Freshman",
    "photo": "TL",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Redshirt Freshman · Prairie View A&M",
    "hometown": "Florence, SC",
    "university": "Prairie View A&M",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Tre is a represented football athlete at Prairie View A&M, based in Florence, SC.",
    "accomplishments": [
      "Redshirt Freshman · RB",
      "Represented at Prairie View A&M",
      "Based in Florence, SC"
    ],
    "stats": [
      [
        "RB",
        "Position"
      ],
      [
        "Redshirt Freshman",
        "Class"
      ],
      [
        "PVA",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "James Madison",
      "logo": "JM",
      "color": "hsl(221 42% 34%)",
      "logoSrc": "assets/schools/james-madison.png"
    },
    "to": {
      "name": "Prairie View A&M",
      "logo": "PVA",
      "color": "hsl(313 42% 34%)",
      "logoSrc": "assets/schools/prairie-view.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/tre-leonard.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "justin-montgomery": {
    "name": "Justin Montgomery",
    "position": "RB · Junior",
    "photo": "JM",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Junior · West Georgia",
    "hometown": "Davie, FL",
    "university": "West Georgia",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Justin is a represented football athlete at West Georgia, based in Davie, FL.",
    "accomplishments": [
      "Junior · RB",
      "Represented at West Georgia",
      "Based in Davie, FL"
    ],
    "stats": [
      [
        "RB",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "WG",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Presbyterian",
      "logo": "P",
      "color": "hsl(276 42% 34%)",
      "logoSrc": "assets/schools/presbyterian.png"
    },
    "to": {
      "name": "West Georgia",
      "logo": "WG",
      "color": "hsl(229 42% 34%)",
      "logoSrc": "assets/schools/west-georgia.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/justin-montgomery.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "jason-oliver": {
    "name": "Jason Oliver",
    "position": "CB · Senior",
    "photo": "JO",
    "basketball": false,
    "agent": "Luke Mazur",
    "athleticLevel": "Senior · San Diego State",
    "hometown": "Bakersfield, CA",
    "university": "San Diego State",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Jason is a represented football athlete at San Diego State, based in Bakersfield, CA.",
    "accomplishments": [
      "Senior · CB",
      "Represented at San Diego State",
      "Based in Bakersfield, CA"
    ],
    "stats": [
      [
        "CB",
        "Position"
      ],
      [
        "Senior",
        "Class"
      ],
      [
        "SD",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Luke",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Sacramento State",
      "logo": "S",
      "color": "hsl(206 42% 34%)",
      "logoSrc": "assets/schools/sacramento-state.png"
    },
    "to": {
      "name": "San Diego State",
      "logo": "SD",
      "color": "hsl(241 42% 34%)",
      "logoSrc": "assets/schools/san-diego-state.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/jason-oliver.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "justin-ross": {
    "name": "Justin Ross",
    "position": "CB · Junior",
    "photo": "JR",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Junior · Virginia",
    "hometown": "Gastonia, NC",
    "university": "Virginia",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Justin is a represented football athlete at Virginia, based in Gastonia, NC.",
    "accomplishments": [
      "Junior · CB",
      "Represented at Virginia",
      "Based in Gastonia, NC"
    ],
    "stats": [
      [
        "CB",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "V",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Navy",
      "logo": "N",
      "color": "hsl(54 42% 34%)",
      "logoSrc": "assets/schools/navy.png"
    },
    "to": {
      "name": "Virginia",
      "logo": "V",
      "color": "hsl(237 42% 34%)",
      "logoSrc": "assets/schools/virginia.png"
    },
    "signed": "January 2026",
    "photoSrc": "assets/portraits/athletes/justin-ross.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "tyrell-russell": {
    "name": "Tyrell Russell",
    "position": "DB · Redshirt Freshman",
    "photo": "TR",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Redshirt Freshman · Toledo",
    "hometown": "Columbus, OH",
    "university": "Toledo",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Tyrell is a represented football athlete at Toledo, based in Columbus, OH.",
    "accomplishments": [
      "Redshirt Freshman · DB",
      "Represented at Toledo",
      "Based in Columbus, OH"
    ],
    "stats": [
      [
        "DB",
        "Position"
      ],
      [
        "Redshirt Freshman",
        "Class"
      ],
      [
        "T",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Columbus area",
      "logo": "TR",
      "color": "#3C096C"
    },
    "to": {
      "name": "Toledo",
      "logo": "T",
      "color": "hsl(135 42% 34%)",
      "logoSrc": "assets/schools/toledo.png"
    },
    "photoSrc": "assets/portraits/athletes/tyrell-russell.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "trajan-sinatra": {
    "name": "Trajan Sinatra",
    "position": "K · Junior",
    "photo": "TS",
    "basketball": false,
    "agent": "Tony Storniolo",
    "athleticLevel": "Junior · San Jose State",
    "hometown": "San Jose, CA",
    "university": "San Jose State",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Trajan is a represented football athlete at San Jose State, based in San Jose, CA.",
    "accomplishments": [
      "Junior · K",
      "Represented at San Jose State",
      "Based in San Jose, CA"
    ],
    "stats": [
      [
        "K",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "SJ",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Tony",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "San Jose area",
      "logo": "TS",
      "color": "#3C096C"
    },
    "to": {
      "name": "San Jose State",
      "logo": "SJ",
      "color": "hsl(0 42% 34%)",
      "logoSrc": "assets/schools/san-jose-state.png"
    },
    "photoSrc": "assets/portraits/athletes/trajan-sinatra.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "calvin-smith-jr": {
    "name": "Calvin Smith Jr.",
    "position": "RB · Sophomore",
    "photo": "CS",
    "basketball": false,
    "agent": "Shane Simpson",
    "athleticLevel": "Sophomore · SE Louisiana",
    "hometown": "New Orleans, LA",
    "university": "SE Louisiana",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Calvin is a represented football athlete at SE Louisiana, based in New Orleans, LA.",
    "accomplishments": [
      "Sophomore · RB",
      "Represented at SE Louisiana",
      "Based in New Orleans, LA"
    ],
    "stats": [
      [
        "RB",
        "Position"
      ],
      [
        "Sophomore",
        "Class"
      ],
      [
        "SL",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Shane",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "New Orleans area",
      "logo": "CS",
      "color": "#3C096C"
    },
    "to": {
      "name": "SE Louisiana",
      "logo": "SL",
      "color": "hsl(129 42% 34%)",
      "logoSrc": "assets/schools/se-louisiana.png"
    },
    "photoSrc": "assets/portraits/athletes/calvin-smith-jr.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "cal-swanson": {
    "name": "Cal Swanson",
    "position": "QB · Junior",
    "photo": "CS",
    "basketball": false,
    "agent": "Tony Storniolo",
    "athleticLevel": "Junior · Holy Cross",
    "hometown": "Ardmore, OK",
    "university": "Holy Cross",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Cal is a represented football athlete at Holy Cross, based in Ardmore, OK.",
    "accomplishments": [
      "Junior · QB",
      "Represented at Holy Cross",
      "Based in Ardmore, OK"
    ],
    "stats": [
      [
        "QB",
        "Position"
      ],
      [
        "Junior",
        "Class"
      ],
      [
        "HC",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Tony",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "Ardmore area",
      "logo": "CS",
      "color": "#3C096C"
    },
    "to": {
      "name": "Holy Cross",
      "logo": "HC",
      "color": "hsl(68 42% 34%)",
      "logoSrc": "assets/schools/holy-cross.png"
    },
    "photoSrc": "assets/portraits/athletes/cal-swanson.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  },
  "mytrell-tillman": {
    "name": "Mytrell Tillman",
    "position": "OL · Freshman",
    "photo": "MT",
    "basketball": false,
    "agent": "Tony Storniolo",
    "athleticLevel": "Freshman · Grambling State",
    "hometown": "East St. Louis, IL",
    "university": "Grambling State",
    "presentability": "Represented athlete with partnership-ready media presence.",
    "bio": "Mytrell is a represented football athlete at Grambling State, based in East St. Louis, IL.",
    "accomplishments": [
      "Freshman · OL",
      "Represented at Grambling State",
      "Based in East St. Louis, IL"
    ],
    "stats": [
      [
        "OL",
        "Position"
      ],
      [
        "Freshman",
        "Class"
      ],
      [
        "G",
        "Program"
      ],
      [
        "Represented",
        "Status"
      ],
      [
        "Tony",
        "Agent"
      ],
      [
        "Football",
        "Sport"
      ]
    ],
    "status": "represented",
    "from": {
      "name": "East St. Louis area",
      "logo": "MT",
      "color": "#3C096C"
    },
    "to": {
      "name": "Grambling State",
      "logo": "G",
      "color": "hsl(178 42% 34%)",
      "logoSrc": "assets/schools/grambling-state.png"
    },
    "photoSrc": "assets/portraits/athletes/mytrell-tillman.jpg",
    "photoPosition": "center 22%",
    "photoPositionRoster": "center top"
  }
};
if (typeof window !== 'undefined') {
  window.ATHLETE_ORDER = ATHLETE_ORDER;
  window.ATHLETES = ATHLETES;
}
