/** Official athletics / institutional logos for transfer wire rows and commit cards. */
export const SCHOOL_LOGO_SRC = {
  'University of Texas': 'assets/schools/texas.png',
  'Duke University': 'assets/schools/duke.png',
  'University of Oregon': 'assets/schools/oregon.png',
  'Ohio State University': 'assets/schools/ohio-state.png',
  'Oregon State': 'assets/schools/oregon-state.png',
  'Iowa State': 'assets/schools/iowa-state.png',
  'Virginia': 'assets/schools/virginia.png',
  'Navy': 'assets/schools/navy.png',
  'Sacramento State': 'assets/schools/sacramento-state.png',
  'San Diego State': 'assets/schools/san-diego-state.png',
  'Toledo': 'assets/schools/toledo.png',
  'James Madison': 'assets/schools/james-madison.png',
  'Drake': 'assets/schools/drake.png',
  'Western New Mexico': 'assets/schools/western-new-mexico.png',
  'Nevada': 'assets/schools/nevada.png',
  'Merrimack': 'assets/schools/merrimack.png',
  'New Mexico State': 'assets/schools/new-mexico-state.png',
  'Eastern Washington': 'assets/schools/eastern-washington.png',
  'Presbyterian': 'assets/schools/presbyterian.png',
  'West Georgia': 'assets/schools/west-georgia.png',
  'Prairie View A&M': 'assets/schools/prairie-view.png',
  'Allen': 'assets/schools/allen.png',
  'Johnson C. Smith': 'assets/schools/johnson-c-smith.png',
  'Harding': 'assets/schools/harding.png',
  'Iowa Central CC': 'assets/schools/iowa-central.png',
  UTGRV: 'assets/schools/utrgv.png',
  'University of Texas Rio Grande Valley': 'assets/schools/utrgv.png',
  Mercyhurst: 'assets/schools/mercyhurst.png',
  'Gardner-Webb': 'assets/schools/gardner-webb.png',
  Bryant: 'assets/schools/bryant.png',
  'New Hampshire': 'assets/schools/new-hampshire.png',
  'Western Michigan': 'assets/schools/western-michigan.png',
  Hawaii: 'assets/schools/hawaii.png',
  Valparaiso: 'assets/schools/valparaiso.png',
  'San Jose State': 'assets/schools/san-jose-state.png',
  'SE Louisiana': 'assets/schools/se-louisiana.png',
  'Holy Cross': 'assets/schools/holy-cross.png',
  'Grambling State': 'assets/schools/grambling-state.png',
};

export function schoolLogoSrc(school) {
  return SCHOOL_LOGO_SRC[school] || null;
}
